#ssh root@38.207.179.64 -p 10612
#
#SSIaHWkGriXgyTcPqc12krMDtCCZqgc4SxaeNIQP9XQ=
#key = "ajc8+8QkVaGz2Wyu9oAWtdHq8W65XvupizmH45H+l9w="
#key = "Xo2R4NXpQ2GqPYkhNG0SWHQSY1M84+JmS+Q0gLWtTek="
key = "SSIaHWkGriXgyTcPqc12krMDtCCZqgc4SxaeNIQP9XQ="
